apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: keda-temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: temporal-worker
          image: temporal-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090 # Expose Prometheus metrics
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal-dev.keda-temporal.svc.cluster.local:7233"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-worker-metrics
  namespace: keda-temporal
spec:
  selector:
    app: temporal-worker
  ports:
    - port: 9090
      targetPort: 9090
      name: metrics
